_wandb:
    value:
        cli_version: 0.19.2
        m: []
        python_version: 3.11.0
        t:
            "1":
                - 12
                - 55
            "2":
                - 12
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.0
            "5": 0.19.2
            "8":
                - 5
            "12": 0.19.2
            "13": linux-x86_64
