# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout repo and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build DQC
      run: |
        chmod +x .github/workflows/build.sh
        ./.github/workflows/build.sh
    - name: Run test
      run: |
        pytest dqc/test/ --cov=./ --cov-report=xml --durations=10
    - name: Run examples
      run: |
        for f in examples/*.py; do echo "$f"; python "$f"; done
    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml # optional
        flags: unittests # optional
        name: codecov-dqc # optional
